baseURL = "https://haoaboutme.github.io/MyPortfolio/"
languageCode = 'vi'
title = 'Portfolio - Nguyá»…n LÃª HoÃ n Háº£o'
theme = 'virgo'

hasCJKLanguage = true
summaryLength = 80
enableGitInfo = true
timeZone = 'Asia/Ho_Chi_Minh'
ignoreLogs = ['warning-partial-superfluous-prefix']

[pagination]
  pagerSize = 10000

[params]
    dark = false                            # Máº·c Ä‘á»‹nh cháº¿ Ä‘á»™ sÃ¡ng
    author = 'Nguyá»…n LÃª HoÃ n Háº£o'
    slogan = 'To Infinity and Beyond'        # Slogan cho homepage
    startDate = 2024                        # 'Copyright Â© 2024 - hiá»‡n táº¡i'
    # KÃ­ch hoáº¡t hiá»‡u á»©ng chuyá»ƒn Ä‘á»™ng khi táº£i trang
    hasActiveAnimate = true
    # KÃ­ch hoáº¡t hiá»‡u á»©ng há»™p ná»•i
    # hasActiveFloatingBox = true
    # Trang bÃ i viáº¿t cÃ³ hiá»ƒn thá»‹ cÃ¡c bÃ i viáº¿t liÃªn quan (khu vá»±c bÃªn trÃ¡i trang)
    isShowRelativePosts = true
    # Trang Ä‘iá»u hÆ°á»›ng bÃªn pháº£i cÃ³ hiá»ƒn thá»‹ mini tÃ¬m kiáº¿m Bing
    isShowMinishipBoxOfNav = true
    # Trang Ä‘iá»u hÆ°á»›ng cÃ³ hiá»ƒn thá»‹ khu vá»±c tÃ¬m kiáº¿m trÃªn cÃ¹ng
    isShowShipBoxOfNav = true
    # Trang Ä‘iá»u hÆ°á»›ng cÃ³ hiá»ƒn thá»‹ tÃ¬m kiáº¿m trong trang (tÃ¬m kiáº¿m ná»™i dung bÃ i viáº¿t)
    # ... Desktop tá»± Ä‘á»™ng cáº­p nháº­t cache bÃ i viáº¿t hÃ ng ngÃ y
    # ... Mobile tá»± Ä‘á»™ng cáº­p nháº­t cache bÃ i viáº¿t hÃ ng thÃ¡ng
    # ... CÃ³ thá»ƒ nháº¥p vÃ o biá»ƒu tÆ°á»£ng bÃªn trÃ¡i Ä‘á»ƒ cáº­p nháº­t cache má»›i nháº¥t
    isShowLocalSearch = true
    # Trang Ä‘iá»u hÆ°á»›ng cÃ³ hiá»ƒn thá»‹ danh sÃ¡ch bÃ i viáº¿t gáº§n Ä‘Ã¢y
    isShowRecentPostsOfNav = true

    # KÃ­ch hoáº¡t cháº¿ Ä‘á»™ cool, mÃ¡t máº» nhÆ°ng tiÃªu tá»‘n tÃ i nguyÃªn nhiá»u hÆ¡n,
    # TrÃ¬nh duyá»‡t cÃ³ cache, sau khi thay Ä‘á»•i báº¯t buá»™c refresh trang (phÃ­m táº¯t Ctrl+Shift+R) hoáº·c khá»Ÿi Ä‘á»™ng láº¡i dá»‹ch vá»¥ local,
    # ------------------
    # <Cáº­p nháº­t> BÃ¢y giá» cÃ³ thá»ƒ trá»±c tiáº¿p chá»‰nh sá»­a hÃ¬nh ná»n vÃ  Ä‘á»™ trong suá»‘t cá»§a máº·t náº¡ hÃ¬nh ná»n á»Ÿ Ä‘Ã¢y
    # - coolBackground file náº±m trong thÆ° má»¥c `/static/imgs/bg`, máº·c Ä‘á»‹nh lÃ  `default.jpg`
    # - coolOpacity máº·c Ä‘á»‹nh lÃ  0.81, Ä‘á»™ trong suá»‘t mÃ u ná»n, tá»« 0 ~ 1
    # - coolSaturate máº·c Ä‘á»‹nh lÃ  180%, Ä‘á»™ bÃ£o hÃ²a mÃ u ná»n, tá»« 0% ~ 200%
    # - coolBlur máº·c Ä‘á»‹nh lÃ  6px, Ä‘á»™ má» mÃ u ná»n, sá»‘ cÃ ng lá»›n cÃ ng má»
    hasActiveCool = true
    coolBackground = 'color.jpg'
    coolOpacity = 0.69 # 0.86
    coolSaturate = '180%'
    coolBlur = '6px'
    
    # HÃ¬nh áº£nh/vÄƒn báº£n trang chá»§
    [params.img]
        # Máº·c Ä‘á»‹nh tÃ­ch há»£p sáºµn `cat.svg â€¦â€¦`, táº¥t nhiÃªn báº¡n cÃ³ thá»ƒ
        # Ä‘áº·t hÃ¬nh áº£nh yÃªu thÃ­ch vÃ o thÆ° má»¥c `static/imgs/` vÃ  tham chiáº¿u trong `src`,
        # âŒ Báº¡n cÅ©ng cÃ³ thá»ƒ Ä‘iá»u chá»‰nh kÃ­ch thÆ°á»›c hiá»ƒn thá»‹ hÃ¬nh áº£nh qua `width`,
        # âŒ Náº¿u Ä‘áº·t `width` thÃ nh '' hoáº·c 0,
        # âŒ sáº½ sá»­ dá»¥ng kÃ­ch thÆ°á»›c Ä‘á»™ phÃ¢n giáº£i gá»‘c cá»§a hÃ¬nh áº£nh
        # âŒ width = 90
        # ğŸ”” Má»¥c Ä‘Ã­ch sá»­ dá»¥ng biá»ƒu tÆ°á»£ng Ä‘Ã£ thay Ä‘á»•i, khÃ´ng cÃ²n há»— trá»£ Ä‘áº·t kÃ­ch thÆ°á»›c á»Ÿ Ä‘Ã¢y, nhÆ°ng
        # Má»›i há»— trá»£ Ä‘áº·t mÃ u ná»n,
        # Äáº·t background thÃ nh '', máº·c Ä‘á»‹nh lÃ  `#000`
        # ! Äá»ƒ Ä‘áº£m báº£o hiá»‡u quáº£ hiá»ƒn thá»‹, khuyáº¿n nghá»‹ chá»n hÃ¬nh áº£nh tá»· lá»‡ 1:1
        # src = 'cat.svg'
        src = 'wukong.png'
        background = '#0003'
        # Gáº¯n chá»©c nÄƒng liÃªn káº¿t nháº¥p chuá»™t cho hÃ¬nh áº£nh nÃ y, máº·c Ä‘á»‹nh lÃ  `/about`, táº¥t nhiÃªn
        # báº¡n cÅ©ng cÃ³ thá»ƒ Ä‘á»‹nh nghÄ©a thÃ nh báº¥t ká»³ liÃªn káº¿t nÃ o báº¡n muá»‘n
        link = '/about'

    [params.contact]
        icp = 'KhÃ´ng bao giá» trá»Ÿ thÃ nh con ngÆ°á»i mÃ  ta tá»«ng ghÃ©t bá»'          # ThÃ´ng tin Ä‘Äƒng kÃ½, náº¿u khÃ´ng muá»‘n hiá»ƒn thá»‹, Ä‘áº·t thÃ nh '' rá»—ng
        icplink = '/about'                                              # LiÃªn káº¿t Ä‘Äƒng kÃ½
        beian = ''                                                      # ÄÄƒng kÃ½ cÃ´ng an, náº¿u khÃ´ng muá»‘n hiá»ƒn thá»‹, Ä‘áº·t thÃ nh '' rá»—ng
        beiancode = ''                                                  # MÃ£ nháº­n dáº¡ng Ä‘Äƒng kÃ½ cÃ´ng an
        github_user = 'HaoAboutMe'                                     # TÃªn ngÆ°á»i dÃ¹ng Github, widget github trang Ä‘iá»u hÆ°á»›ng sá»­ dá»¥ng
        # wechat = 'imgs/bg/wechat.jpg'                                 # Äá»‹a chá»‰ mÃ£ QR WeChat
        # weibo = 'https://weibo.com/u/6867589681'
        # zhihu = 'https://www.zhihu.com/people/loveminimal'
        # jianshu = 'https://www.jianshu.com/u/eebcc2974936'
        email = 'haoaboutme.1512@gmail.com'
        github = 'https://github.com/HaoAboutMe'
        facebook = 'https://www.facebook.com/haoaboutme.1512'
        # bilibili = 'https://space.bilibili.com/11608450'
        # douyin = 'https://www.douyin.com/user/self'
        # xiaohongshu = 'https://www.xiaohongshu.com/user/profile/60004c750000000001002065'
        # reddit = 'https://www.reddit.com/user/aituyaa'
        # twitter = 'https://twitter.com/aituyaa'
        # mastodon = 'https://mastodon.social/@loveminimal'
        # instagram = 'https://www.instagram.com/aituyaa'
        # youtube = 'https://www.youtube.com/@aituyaa'
        # telegram = 'https://web.telegram.org/k/#@aituyaa'	# 'https://t.me/aituyaa'
        # discord = 'https://discord.com/channels/@me'

        [params.contact.config]
            color = '#696969'                         # MÃ u biá»ƒu tÆ°á»£ng, máº·c Ä‘á»‹nh lÃ  xÃ¡m nháº¡t
            slogan = ''                               # Kháº©u hiá»‡u liÃªn há»‡, khÃ´ng muá»‘n hiá»ƒn thá»‹ cÃ³ thá»ƒ Ä‘á»ƒ trá»‘ng
            # isShowNavLink = true                      # CÃ³ hiá»ƒn thá»‹ liÃªn káº¿t Ä‘iá»u hÆ°á»›ng nhanh bÃªn trÃ¡i thanh liÃªn há»‡ (PS: Trang chá»§ luÃ´n hiá»ƒn thá»‹)
            target = '_self'                          # Äá»‹nh nghÄ©a cÃ¡ch má»Ÿ liÃªn káº¿t Ä‘iá»u hÆ°á»›ng nhanh bÃªn trÃ¡i, _blank trong tab má»›i _self trong tab hiá»‡n táº¡i
            ship = ''                                 # Biá»ƒu tÆ°á»£ng thanh liÃªn há»‡, cho phÃ©p tÃ¹y chá»‰nh liÃªn káº¿t biá»ƒu tÆ°á»£ng nÃ y (/ship cho trang tÃ¬m kiáº¿m cÃ¡ nhÃ¢n hÃ³a liÃªn káº¿t ngoÃ i); áº©n, Ä‘áº·t thÃ nh '' rá»—ng

    # https://utteranc.es/
    # Trong mÃ´i trÆ°á»ng phÃ¡t triá»ƒn (http://localhost:1313/), khÃ´ng kÃ­ch hoáº¡t plugin bÃ¬nh luáº­n,
    # Náº¿u muá»‘n kÃ­ch hoáº¡t trong mÃ´i trÆ°á»ng phÃ¡t triá»ƒn, sá»­a cá»•ng mÃ¡y chá»§, nhÆ° sau
    # hugo server -p=1314
    [params.utterances]
        active = false                            # CÃ³ kÃ­ch hoáº¡t plugin bÃ¬nh luáº­n
        repo = "HaoAboutMe/comment"              # Nháº­p tÃªn repository cá»§a báº¡n
        issueTerm = "pathname"
        theme = "github-light"
        crossorigin = "anonymous"

    # Trong mÃ´i trÆ°á»ng phÃ¡t triá»ƒn (http://localhost:1313/), khÃ´ng kÃ­ch hoáº¡t plugin bÃ¬nh luáº­n,
    # Náº¿u muá»‘n kÃ­ch hoáº¡t trong mÃ´i trÆ°á»ng phÃ¡t triá»ƒn, sá»­a cá»•ng mÃ¡y chá»§, nhÆ° sau
    # hugo server -p=1314
    # ---------
    # Trong https://giscus.app/, chá»n cáº¥u hÃ¬nh sau sáº½ tá»± Ä‘á»™ng táº¡o, nhÆ° data-*
    # Máº·c Ä‘á»‹nh báº­t data-loading="lazy"
    [params.giscus]
        active = false                             # CÃ³ kÃ­ch hoáº¡t plugin bÃ¬nh luáº­n
        repo = "HaoAboutMe/comment"              # Nháº­p tÃªn repository cá»§a báº¡n
        repoId = "R_kgDOJNJQ8g"
        category="General"
        categoryId="DIC_kwDOJNJQ8s4CYl0m"
        mapping = "title"
        inputPosition = "bottom"
        theme = "noborder_light"
        crossorigin = "anonymous"
        lang = "vi"

# CÃ¡c thiáº¿t láº­p sau cho engine phÃ¢n tÃ­ch Markdown,
# Khuyáº¿n nghá»‹ giá»¯ nguyÃªn
[markup]
    [markup.asciidocExt]
        preserveTOC = true
    [markup.highlight]
        # Kiá»ƒu hiá»ƒn thá»‹ khá»‘i mÃ£, hiá»ƒn thá»‹ sá»‘ dÃ²ng
        style = "github"
        lineNos = true
    [markup.tableOfContents]
        endLevel = 4
        ordered = false
        startLevel = 2
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
